#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Mon Apr 12 14:46:13 2021
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_main = wx.Notebook(self, wx.ID_ANY)
        self.notebook_main_Scan = wx.Panel(self.notebook_main, wx.ID_ANY)
        self.radio_box_decode = wx.RadioBox(self.notebook_main_Scan, wx.ID_ANY, "Code decoding", choices=["Local", "Web"], majorDimension=2, style=wx.RA_SPECIFY_COLS)
        self.label_auth_status_label = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Auth Status:")
        self.label_auth_status = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "     ")
        self.button_auth = wx.Button(self.notebook_main_Scan, wx.ID_ANY, "Authorise this app on DigiKey")
        self.choice_camera = wx.Choice(self.notebook_main_Scan, wx.ID_ANY, choices=[])
        self.button_update_cam_list = wx.Button(self.notebook_main_Scan, wx.ID_ANY, "Update Cameras")
        self.button_camera = wx.Button(self.notebook_main_Scan, wx.ID_ANY, "Enable Camera")
        self.bitmap_camera = wx.StaticBitmap(self.notebook_main_Scan, wx.ID_ANY, wx.Bitmap(640, 480))
        self.text_ctrl_name = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_loc = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_qty = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_supplier_pn = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_manufacturer_pn = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_cat = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_manufacturer = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_supplier = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_prj = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_desc = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_cust_ref = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.text_ctrl_comment = wx.TextCtrl(self.notebook_main_Scan, wx.ID_ANY, "")
        self.button_save = wx.Button(self.notebook_main_Scan, wx.ID_ANY, "Save")
        self.button_cancel = wx.Button(self.notebook_main_Scan, wx.ID_ANY, "Cancel")
        self.button_delete = wx.Button(self.notebook_main_Scan, wx.ID_ANY, "Delete")
        self.notebook_main_Search = wx.Panel(self.notebook_main, wx.ID_ANY)
        self.notebook_search = wx.Notebook(self.notebook_main_Search, wx.ID_ANY, style=wx.NB_LEFT)
        self.notebook_search_Basic = wx.Panel(self.notebook_search, wx.ID_ANY)
        self.text_ctrl_basic_search = wx.SearchCtrl(self.notebook_search_Basic, wx.ID_ANY, "")
        self.notebook_search_Advanced = wx.Panel(self.notebook_search, wx.ID_ANY)
        self.choice_search_1 = wx.Choice(self.notebook_search_Advanced, wx.ID_ANY, choices=["Name", "Supplier P/N", "Manufacturer P/N", "Location", "Quantity", "Category", "Description", "Supplier", "Manufacturer", "Used by Project", "Customer Ref", "Comment"])
        self.text_ctrl_adv_search_1 = wx.TextCtrl(self.notebook_search_Advanced, wx.ID_ANY, "")
        self.choice_logic_1 = wx.Choice(self.notebook_search_Advanced, wx.ID_ANY, choices=["AND", "OR"])
        self.choice_search_2 = wx.Choice(self.notebook_search_Advanced, wx.ID_ANY, choices=["Name", "Supplier P/N", "Manufacturer P/N", "Location", "Quantity", "Category", "Description", "Supplier", "Manufacturer", "Used by Project", "Customer Ref", "Comment"])
        self.text_ctrl_adv_search_2 = wx.TextCtrl(self.notebook_search_Advanced, wx.ID_ANY, "")
        self.choice_logic_2 = wx.Choice(self.notebook_search_Advanced, wx.ID_ANY, choices=["AND", "OR"])
        self.choice_search_3 = wx.Choice(self.notebook_search_Advanced, wx.ID_ANY, choices=["Name", "Supplier P/N", "Manufacturer P/N", "Location", "Quantity", "Category", "Description", "Supplier", "Manufacturer", "Used by Project", "Customer Ref", "Comment"])
        self.text_ctrl_adv_search_3 = wx.TextCtrl(self.notebook_search_Advanced, wx.ID_ANY, "")
        self.button_search_adv = wx.Button(self.notebook_search_Advanced, wx.ID_ANY, "Advanced Search")
        self.button_clear = wx.Button(self.notebook_search_Advanced, wx.ID_ANY, "Clear Search")
        self.grid_results = wx.grid.Grid(self.notebook_main_Search, wx.ID_ANY, size=(1, 1))
        self.button_view = wx.Button(self.notebook_main_Search, wx.ID_ANY, "View...")
        self.button_checkout = wx.Button(self.notebook_main_Search, wx.ID_ANY, "Check Out...")
        self.button_checkin = wx.Button(self.notebook_main_Search, wx.ID_ANY, "Check In...")
        self.button_edit = wx.Button(self.notebook_main_Search, wx.ID_ANY, "Edit...")
        self.notebook_main_Help = wx.Panel(self.notebook_main, wx.ID_ANY)
        self.text_ctrl_help_url = wx.TextCtrl(self.notebook_main_Help, wx.ID_ANY, "https://github.com/Ray457/Electrons-Inventory", style=wx.TE_CENTRE | wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_RADIOBOX, self.radiobox_decode_handler, self.radio_box_decode)
        self.Bind(wx.EVT_BUTTON, self.btn_auth, self.button_auth)
        self.Bind(wx.EVT_BUTTON, self.btn_update_cam_list, self.button_update_cam_list)
        self.Bind(wx.EVT_BUTTON, self.btn_enable_camera, self.button_camera)
        self.Bind(wx.EVT_TEXT_ENTER, self.test_enter, self.text_ctrl_name)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_loc)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_qty)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_supplier_pn)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_manufacturer_pn)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_cat)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_manufacturer)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_supplier)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_prj)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_desc)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_cust_ref)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_save, self.text_ctrl_comment)
        self.Bind(wx.EVT_BUTTON, self.btn_save, self.button_save)
        self.Bind(wx.EVT_BUTTON, self.btn_cancel, self.button_cancel)
        self.Bind(wx.EVT_BUTTON, self.btn_delete, self.button_delete)
        self.Bind(wx.EVT_SEARCHCTRL_SEARCH_BTN, self.btn_search_basic, self.text_ctrl_basic_search)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_search_basic, self.text_ctrl_basic_search)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_search_adv, self.text_ctrl_adv_search_1)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_search_adv, self.text_ctrl_adv_search_2)
        self.Bind(wx.EVT_TEXT_ENTER, self.btn_search_adv, self.text_ctrl_adv_search_3)
        self.Bind(wx.EVT_BUTTON, self.btn_search_adv, self.button_search_adv)
        self.Bind(wx.EVT_BUTTON, self.btn_clear_adv_search, self.button_clear)
        self.Bind(wx.grid.EVT_GRID_CMD_CELL_LEFT_CLICK, self.results_row_selected, self.grid_results)
        self.Bind(wx.grid.EVT_GRID_CMD_SELECT_CELL, self.results_cell_selected, self.grid_results)
        self.Bind(wx.EVT_BUTTON, self.btn_view_result, self.button_view)
        self.Bind(wx.EVT_BUTTON, self.btn_checkout, self.button_checkout)
        self.Bind(wx.EVT_BUTTON, self.btn_checkin, self.button_checkin)
        self.Bind(wx.EVT_BUTTON, self.btn_edit, self.button_edit)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.main_notebook_changed, self.notebook_main)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("FSAE:47 Electrons Inventory System")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("storage.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.radio_box_decode.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.radio_box_decode.SetSelection(0)
        self.label_auth_status_label.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.label_auth_status_label.Enable(False)
        self.label_auth_status.SetBackgroundColour(wx.Colour(255, 127, 127))
        self.label_auth_status.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.label_auth_status.Enable(False)
        self.button_auth.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_auth.Enable(False)
        self.choice_camera.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_update_cam_list.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_camera.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.bitmap_camera.SetMinSize((640, 480))
        self.text_ctrl_name.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_loc.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_qty.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_supplier_pn.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_manufacturer_pn.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_cat.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_manufacturer.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_supplier.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_prj.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_desc.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_cust_ref.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_comment.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_save.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_cancel.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_delete.SetBackgroundColour(wx.Colour(255, 127, 0))
        self.button_delete.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_delete.Enable(False)
        self.text_ctrl_basic_search.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_basic_search.ShowCancelButton(True)
        self.text_ctrl_basic_search.SetDescriptiveText("Search in all columns...")
        self.choice_search_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_adv_search_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.choice_logic_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.choice_logic_1.SetSelection(0)
        self.choice_search_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_adv_search_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.choice_logic_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.choice_logic_2.SetSelection(0)
        self.choice_search_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_adv_search_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_search_adv.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_clear.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.grid_results.CreateGrid(22, 12)
        self.grid_results.EnableEditing(0)
        self.grid_results.EnableDragRowSize(0)
        self.grid_results.SetSelectionMode(wx.grid.Grid.SelectRows)
        self.grid_results.SetColLabelValue(0, "Name")
        self.grid_results.SetColLabelValue(1, "Supplier P/N")
        self.grid_results.SetColLabelValue(2, "Manufacturer P/N")
        self.grid_results.SetColLabelValue(3, "Location")
        self.grid_results.SetColLabelValue(4, "Quantity")
        self.grid_results.SetColLabelValue(5, "Category")
        self.grid_results.SetColLabelValue(6, "Description")
        self.grid_results.SetColLabelValue(7, "Supplier")
        self.grid_results.SetColLabelValue(8, "Manufacturer")
        self.grid_results.SetColLabelValue(9, "Used by Project")
        self.grid_results.SetColLabelValue(10, "Customer Ref")
        self.grid_results.SetColLabelValue(11, "Comment")
        self.button_view.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_view.Enable(False)
        self.button_checkout.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_checkout.Enable(False)
        self.button_checkin.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_checkin.Enable(False)
        self.button_edit.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_edit.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_main = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.GridSizer(1, 1, 0, 0)
        sizer_add_LR = wx.BoxSizer(wx.HORIZONTAL)
        sizer_add_R = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(3, 4, 0, 0)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_add_L = wx.BoxSizer(wx.VERTICAL)
        sizer_camera = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(self.radio_box_decode, 0, wx.ALL, 5)
        sizer_6.Add(self.label_auth_status_label, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_6.Add(self.label_auth_status, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_6.Add(self.button_auth, 1, wx.ALL | wx.EXPAND, 5)
        sizer_add_L.Add(sizer_6, 0, wx.EXPAND, 0)
        label_camera_num = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Camera Number:")
        label_camera_num.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_camera.Add(label_camera_num, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)
        sizer_camera.Add(self.choice_camera, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)
        sizer_camera.Add(self.button_update_cam_list, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        sizer_camera.Add(self.button_camera, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        sizer_add_L.Add(sizer_camera, 0, wx.EXPAND, 0)
        camera_div = wx.StaticLine(self.notebook_main_Scan, wx.ID_ANY)
        sizer_add_L.Add(camera_div, 0, wx.EXPAND, 0)
        sizer_add_L.Add(self.bitmap_camera, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_add_LR.Add(sizer_add_L, 1, wx.EXPAND, 0)
        static_line_3 = wx.StaticLine(self.notebook_main_Scan, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_add_LR.Add(static_line_3, 0, wx.EXPAND, 0)
        label_name = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Name:")
        label_name.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_5.Add(label_name, 0, wx.ALL, 5)
        sizer_5.Add(self.text_ctrl_name, 1, wx.ALL, 5)
        label_loc = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Location: *")
        label_loc.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_5.Add(label_loc, 0, wx.ALL, 5)
        sizer_5.Add(self.text_ctrl_loc, 0, wx.ALL, 5)
        label_qty = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Quantity: *")
        label_qty.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_5.Add(label_qty, 0, wx.ALL, 5)
        sizer_5.Add(self.text_ctrl_qty, 0, wx.ALL, 5)
        sizer_add_R.Add(sizer_5, 0, wx.EXPAND, 0)
        static_line_4 = wx.StaticLine(self.notebook_main_Scan, wx.ID_ANY)
        sizer_add_R.Add(static_line_4, 0, wx.EXPAND, 0)
        label_supplier_pn = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Supplier P/N:")
        label_supplier_pn.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_supplier_pn, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_supplier_pn, 0, wx.ALL | wx.EXPAND, 5)
        label_manufacturer_pn = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Manufacturer P/N:")
        label_manufacturer_pn.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_manufacturer_pn, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_manufacturer_pn, 0, wx.ALL | wx.EXPAND, 5)
        label_cat = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Category:")
        label_cat.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_cat, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_cat, 0, wx.ALL | wx.EXPAND, 5)
        label_manufacturer = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Manufacturer:")
        label_manufacturer.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_manufacturer, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_manufacturer, 0, wx.ALL | wx.EXPAND, 5)
        label_supplier = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Supplier:")
        label_supplier.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_supplier, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_supplier, 0, wx.ALL | wx.EXPAND, 5)
        label_prj = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Used by Project:")
        label_prj.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_prj, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.text_ctrl_prj, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.AddGrowableRow(1)
        grid_sizer_1.AddGrowableRow(2)
        grid_sizer_1.AddGrowableCol(0)
        grid_sizer_1.AddGrowableCol(1)
        grid_sizer_1.AddGrowableCol(2)
        grid_sizer_1.AddGrowableCol(3)
        sizer_add_R.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        static_line_5 = wx.StaticLine(self.notebook_main_Scan, wx.ID_ANY)
        sizer_add_R.Add(static_line_5, 0, wx.EXPAND, 0)
        label_desc = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Description:")
        label_desc.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_2.Add(label_desc, 0, wx.ALL, 5)
        grid_sizer_2.Add(self.text_ctrl_desc, 0, wx.ALL | wx.EXPAND, 5)
        label_cust_ref = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Customer Ref:")
        label_cust_ref.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_2.Add(label_cust_ref, 0, wx.ALL, 5)
        grid_sizer_2.Add(self.text_ctrl_cust_ref, 0, wx.ALL | wx.EXPAND, 5)
        label_comment = wx.StaticText(self.notebook_main_Scan, wx.ID_ANY, "Comment:")
        label_comment.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_2.Add(label_comment, 0, wx.ALL, 5)
        grid_sizer_2.Add(self.text_ctrl_comment, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableRow(1)
        grid_sizer_2.AddGrowableRow(2)
        grid_sizer_2.AddGrowableCol(1)
        sizer_add_R.Add(grid_sizer_2, 2, wx.ALL | wx.EXPAND, 2)
        static_line_6 = wx.StaticLine(self.notebook_main_Scan, wx.ID_ANY)
        sizer_add_R.Add(static_line_6, 0, wx.EXPAND, 0)
        sizer_add_R.Add(self.button_save, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 5)
        sizer_add_R.Add(self.button_cancel, 1, wx.ALL | wx.EXPAND, 5)
        sizer_add_R.Add(self.button_delete, 0, wx.ALL | wx.EXPAND, 5)
        sizer_add_LR.Add(sizer_add_R, 1, wx.EXPAND, 0)
        self.notebook_main_Scan.SetSizer(sizer_add_LR)
        sizer_1.Add(self.text_ctrl_basic_search, 0, wx.ALL | wx.EXPAND, 5)
        self.notebook_search_Basic.SetSizer(sizer_1)
        sizer_8.Add(self.choice_search_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        label_1 = wx.StaticText(self.notebook_search_Advanced, wx.ID_ANY, "Contains")
        label_1.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_8.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_8.Add(self.text_ctrl_adv_search_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_8.Add(self.choice_logic_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_8.Add(self.choice_search_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        label_3 = wx.StaticText(self.notebook_search_Advanced, wx.ID_ANY, "Contains")
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_8.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_8.Add(self.text_ctrl_adv_search_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_8.Add(self.choice_logic_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_8.Add(self.choice_search_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        label_5 = wx.StaticText(self.notebook_search_Advanced, wx.ID_ANY, "Contains")
        label_5.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_8.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_8.Add(self.text_ctrl_adv_search_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_3.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_11.Add(self.button_search_adv, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        sizer_11.Add(self.button_clear, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_11, 1, wx.EXPAND, 0)
        self.notebook_search_Advanced.SetSizer(sizer_3)
        self.notebook_search.AddPage(self.notebook_search_Basic, "Basic")
        self.notebook_search.AddPage(self.notebook_search_Advanced, "Advanced")
        sizer_2.Add(self.notebook_search, 2, wx.ALL | wx.EXPAND, 5)
        sizer_2.Add(self.grid_results, 11, wx.ALL | wx.EXPAND, 5)
        sizer_7.Add(self.button_view, 1, wx.ALL | wx.EXPAND, 5)
        sizer_7.Add(self.button_checkout, 1, wx.ALL | wx.EXPAND, 5)
        sizer_7.Add(self.button_checkin, 1, wx.ALL | wx.EXPAND, 5)
        sizer_7.Add(self.button_edit, 1, wx.ALL | wx.EXPAND, 5)
        sizer_2.Add(sizer_7, 1, wx.EXPAND, 0)
        self.notebook_main_Search.SetSizer(sizer_2)
        label_help = wx.StaticText(self.notebook_main_Help, wx.ID_ANY, "Please visit the GitHub page for help and documentation:", style=wx.ALIGN_CENTER)
        label_help.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_4.Add(label_help, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_4.Add(self.text_ctrl_help_url, 0, wx.ALL | wx.EXPAND, 5)
        self.notebook_main_Help.SetSizer(sizer_4)
        self.notebook_main.AddPage(self.notebook_main_Scan, "Scan/Edit")
        self.notebook_main.AddPage(self.notebook_main_Search, "Search/View")
        self.notebook_main.AddPage(self.notebook_main_Help, "Help")
        sizer_main.Add(self.notebook_main, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        sizer_main.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def radiobox_decode_handler(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'radiobox_decode_handler' not implemented!")
        event.Skip()

    def btn_auth(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_auth' not implemented!")
        event.Skip()

    def btn_update_cam_list(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_update_cam_list' not implemented!")
        event.Skip()

    def btn_enable_camera(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_enable_camera' not implemented!")
        event.Skip()

    def test_enter(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'test_enter' not implemented!")
        event.Skip()

    def btn_save(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_save' not implemented!")
        event.Skip()

    def btn_cancel(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_cancel' not implemented!")
        event.Skip()

    def btn_delete(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_delete' not implemented!")
        event.Skip()

    def btn_search_basic(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_search_basic' not implemented!")
        event.Skip()

    def btn_search_adv(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_search_adv' not implemented!")
        event.Skip()

    def btn_clear_adv_search(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_clear_adv_search' not implemented!")
        event.Skip()

    def results_row_selected(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'results_row_selected' not implemented!")
        event.Skip()

    def results_cell_selected(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'results_cell_selected' not implemented!")
        event.Skip()

    def btn_view_result(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_view_result' not implemented!")
        event.Skip()

    def btn_checkout(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_checkout' not implemented!")
        event.Skip()

    def btn_checkin(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_checkin' not implemented!")
        event.Skip()

    def btn_edit(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'btn_edit' not implemented!")
        event.Skip()

    def main_notebook_changed(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'main_notebook_changed' not implemented!")
        event.Skip()

# end of class MainFrame

class CheckoutDialog_GUI(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CheckoutDialog_GUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_checkout_item_name = wx.StaticText(self, wx.ID_ANY, "-")
        self.text_ctrl_proj = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_quantity = wx.StaticText(self, wx.ID_ANY, "-")
        self.spin_ctrl_checkout_quantity = wx.SpinCtrl(self, wx.ID_ANY, "", min=0, max=1000)
        self.button_checkout_ok = wx.Button(self, wx.ID_ANY, "OK")
        self.button_checkout_cancel = wx.Button(self, wx.ID_ANY, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_checkout_ok, self.button_checkout_ok)
        self.Bind(wx.EVT_BUTTON, self.btn_checkout_cancel, self.button_checkout_cancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CheckoutDialog_GUI.__set_properties
        self.SetTitle("Check Out")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("takeaway.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.label_checkout_item_name.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.text_ctrl_proj.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.label_quantity.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.spin_ctrl_checkout_quantity.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_checkout_ok.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_checkout_cancel.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CheckoutDialog_GUI.__do_layout
        grid_sizer_3 = wx.GridSizer(5, 2, 0, 0)
        label_checkout = wx.StaticText(self, wx.ID_ANY, "Checking out:")
        label_checkout.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_3.Add(label_checkout, 1, wx.ALL, 5)
        grid_sizer_3.Add(self.label_checkout_item_name, 1, wx.ALL, 5)
        label_project = wx.StaticText(self, wx.ID_ANY, "Used by project:")
        label_project.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_3.Add(label_project, 1, wx.ALL, 5)
        grid_sizer_3.Add(self.text_ctrl_proj, 1, wx.ALL | wx.EXPAND, 5)
        label_quantity_label = wx.StaticText(self, wx.ID_ANY, "Current quantity:")
        label_quantity_label.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_3.Add(label_quantity_label, 1, wx.ALL, 5)
        grid_sizer_3.Add(self.label_quantity, 1, wx.ALL, 5)
        label_todeduct = wx.StaticText(self, wx.ID_ANY, "Quantity to deduct:")
        label_todeduct.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_3.Add(label_todeduct, 1, wx.ALL, 5)
        grid_sizer_3.Add(self.spin_ctrl_checkout_quantity, 1, wx.ALL | wx.EXPAND, 5)
        grid_sizer_3.Add(self.button_checkout_ok, 1, wx.ALL | wx.EXPAND, 5)
        grid_sizer_3.Add(self.button_checkout_cancel, 1, wx.ALL | wx.EXPAND, 5)
        self.SetSizer(grid_sizer_3)
        grid_sizer_3.Fit(self)
        grid_sizer_3.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def btn_checkout_ok(self, event):  # wxGlade: CheckoutDialog_GUI.<event_handler>
        print("Event handler 'btn_checkout_ok' not implemented!")
        event.Skip()

    def btn_checkout_cancel(self, event):  # wxGlade: CheckoutDialog_GUI.<event_handler>
        print("Event handler 'btn_checkout_cancel' not implemented!")
        event.Skip()

# end of class CheckoutDialog_GUI

class ViewResultDialog_GUI(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ViewResultDialog_GUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.list_ctrl_view = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_NO_HEADER | wx.LC_REPORT | wx.LC_VRULES)
        self.button_checkout = wx.Button(self, wx.ID_ANY, "Check Out...")
        self.button_checkin = wx.Button(self, wx.ID_ANY, "Check In...")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_checkout, self.button_checkout)
        self.Bind(wx.EVT_BUTTON, self.btn_checkin, self.button_checkin)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ViewResultDialog_GUI.__set_properties
        self.SetTitle("View Result")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("magnifying-glass.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.list_ctrl_view.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.list_ctrl_view.AppendColumn("A", format=wx.LIST_FORMAT_LEFT, width=150)
        self.list_ctrl_view.AppendColumn("B", format=wx.LIST_FORMAT_LEFT, width=400)
        self.button_checkout.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_checkin.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ViewResultDialog_GUI.__do_layout
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(self.list_ctrl_view, 8, wx.ALL | wx.EXPAND, 5)
        sizer_9.Add(self.button_checkout, 1, wx.ALL | wx.EXPAND, 5)
        sizer_9.Add(self.button_checkin, 1, wx.ALL | wx.EXPAND, 5)
        self.SetSizer(sizer_9)
        sizer_9.Fit(self)
        sizer_9.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def btn_checkout(self, event):  # wxGlade: ViewResultDialog_GUI.<event_handler>
        print("Event handler 'btn_checkout' not implemented!")
        event.Skip()

    def btn_checkin(self, event):  # wxGlade: ViewResultDialog_GUI.<event_handler>
        print("Event handler 'btn_checkin' not implemented!")
        event.Skip()

# end of class ViewResultDialog_GUI

class ScanExistingDialog_GUI(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ScanExistingDialog_GUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.button_checkout = wx.Button(self, wx.ID_ANY, "Check Out...")
        self.button_checkin = wx.Button(self, wx.ID_ANY, "Check In...")
        self.button_edit = wx.Button(self, wx.ID_ANY, "Just Edit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_checkout, self.button_checkout)
        self.Bind(wx.EVT_BUTTON, self.btn_checkin, self.button_checkin)
        self.Bind(wx.EVT_BUTTON, self.btn_edit, self.button_edit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ScanExistingDialog_GUI.__set_properties
        self.SetTitle("Existing Item")
        self.button_checkout.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_checkin.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_edit.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ScanExistingDialog_GUI.__do_layout
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        label_message = wx.StaticText(self, wx.ID_ANY, "You scanned an existing item.\nWhat would you like to do?")
        label_message.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_10.Add(label_message, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 30)
        sizer_10.Add(self.button_checkout, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        sizer_10.Add(self.button_checkin, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        sizer_10.Add(self.button_edit, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        self.SetSizer(sizer_10)
        sizer_10.Fit(self)
        sizer_10.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def btn_checkout(self, event):  # wxGlade: ScanExistingDialog_GUI.<event_handler>
        print("Event handler 'btn_checkout' not implemented!")
        event.Skip()

    def btn_checkin(self, event):  # wxGlade: ScanExistingDialog_GUI.<event_handler>
        print("Event handler 'btn_checkin' not implemented!")
        event.Skip()

    def btn_edit(self, event):  # wxGlade: ScanExistingDialog_GUI.<event_handler>
        print("Event handler 'btn_edit' not implemented!")
        event.Skip()

# end of class ScanExistingDialog_GUI

class CheckinDailog_GUI(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CheckinDailog_GUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_checkin_item_name = wx.StaticText(self, wx.ID_ANY, "-")
        self.spin_ctrl_checkin_quantity = wx.SpinCtrl(self, wx.ID_ANY, "", min=0, max=1000)
        self.button_checkin_ok = wx.Button(self, wx.ID_ANY, "OK")
        self.button_checkin_cancel = wx.Button(self, wx.ID_ANY, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_checkin_ok, self.button_checkin_ok)
        self.Bind(wx.EVT_BUTTON, self.btn_checkin_cancel, self.button_checkin_cancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CheckinDailog_GUI.__set_properties
        self.SetTitle("Check In")
        self.label_checkin_item_name.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.spin_ctrl_checkin_quantity.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_checkin_ok.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.button_checkin_cancel.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CheckinDailog_GUI.__do_layout
        grid_sizer_4 = wx.GridSizer(3, 2, 0, 0)
        label_checkin = wx.StaticText(self, wx.ID_ANY, "Checking in:")
        label_checkin.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_4.Add(label_checkin, 1, wx.ALL, 5)
        grid_sizer_4.Add(self.label_checkin_item_name, 1, wx.ALL, 5)
        label_todeduct = wx.StaticText(self, wx.ID_ANY, "Quantity to deduct:")
        label_todeduct.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_4.Add(label_todeduct, 1, wx.ALL, 5)
        grid_sizer_4.Add(self.spin_ctrl_checkin_quantity, 1, wx.ALL | wx.EXPAND, 5)
        grid_sizer_4.Add(self.button_checkin_ok, 1, wx.ALL | wx.EXPAND, 5)
        grid_sizer_4.Add(self.button_checkin_cancel, 1, wx.ALL | wx.EXPAND, 5)
        self.SetSizer(grid_sizer_4)
        grid_sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

    def btn_checkin_ok(self, event):  # wxGlade: CheckinDailog_GUI.<event_handler>
        print("Event handler 'btn_checkin_ok' not implemented!")
        event.Skip()

    def btn_checkin_cancel(self, event):  # wxGlade: CheckinDailog_GUI.<event_handler>
        print("Event handler 'btn_checkin_cancel' not implemented!")
        event.Skip()

# end of class CheckinDailog_GUI

class InvApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class InvApp

if __name__ == "__main__":
    inventory_app = InvApp(0)
    inventory_app.MainLoop()
